#!/bin/bash

#CMD_TARGET='dummy'
#OBJ_TARGET='fibre/strand.o'

if [ ${#CMD_TARGET} -gt 0 ]; then

  echo
  echo "WARNING!! Only building for target $CMD_TARGET"
  echo
  
  TARGET=bin/${CMD_TARGET}__debug

elif [ ${#OBJ_TARGET} -gt 0 ]; then

  echo
  echo "WARNING!! Only building for target $OBJ_TARGET"
  echo
  
  TARGET=src/bts/${OBJ_TARGET}__debug.o
    
fi
  
echo $TARGET

PATH=/usr/local/bin:$PATH
DYLD_LIBRARY_PATH=/usr/local/lib:$DYLD_LIBRARY_PATH
../mrtrix/build debug $TARGET $@ 
