from stress_test_generator import *

set = Set()
set.first_set(StressTestGenerator.SET_SIZE,StressTestGenerator.OBJECT_SIZE)
global objects
global prop_rows
global prop_row_maps

f = open('/home/tclose/Code/Tractography/python/fibre/base/test/output/python_output.txt','w')
f.write("\n\n-------------------------------------\n            INITIAL SET             \n-------------------------------------\n" + str(set) + "\n\n")
f.write("\n\n-------------------------------------\n            SECOND SET             \n-------------------------------------\n" + str(set2) + "\n\n")
set.insert(objects[5][8],1)
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_index(ELEM_PROP_4): ' + str(set.elem_prop_index(ELEM_PROP_4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_elem_prop(ELEM_PROP_2,669)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_7): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_7)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_6,984)
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
set.remove_prop(PROP_3)
f.write("\n\n-------------------------------------\n            5 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.add_elem_prop(ELEM_PROP_4,463)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.copy_extend_elem_prop_row(set2,3,2)
set.copy_extend_elem_prop_row(set2,1,1)
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_9,419)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop(PROP_9): ' + str(set.prop(PROP_9)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_elem_prop(ELEM_PROP_5,661)
f.write("\n\n-------------------------------------\n            10 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.push_back(objects[9][0], ext_prop_row_maps[3])
f.write('set.prop_index(PROP_2): ' + str(set.prop_index(PROP_2)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.erase(1)
set.add_elem_prop(ELEM_PROP_4,815)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_index(PROP_2): ' + str(set.prop_index(PROP_2)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_7,434)
set.insert(objects[5][8],1)
f.write("\n\n-------------------------------------\n            15 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
set.set_extend_elem_prop_row(ext_prop_row_maps[1],4)
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop_row(ext_prop_row_maps[3],4)
set.push_back(objects[5][6], ext_prop_row_maps[7])
set.erase(2)
f.write("\n\n-------------------------------------\n            20 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.insert(objects[1][5],5)
set.push_back(objects[6][1])
f.write('set.elem_prop_index(ELEM_PROP_4): ' + str(set.elem_prop_index(ELEM_PROP_4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_index(ELEM_PROP_4): ' + str(set.elem_prop_index(ELEM_PROP_4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.resize(1,574,0)
set.push_back(objects[0][2])
set.elem_resize(7,511)
f.write("\n\n-------------------------------------\n            25 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.push_back(objects[7][8])
f.write('set.prop(PROP_4): ' + str(set.prop(PROP_4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.get_extend_elem_prop_row(1)
set.elem_resize(8,886)
set.add_extend_elem_props(set2)
set.add_elem_prop(ELEM_PROP_4,734)
f.write("\n\n-------------------------------------\n            30 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.insert(objects[8][4],1)
set.remove_elem_prop(ELEM_PROP_3)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.insert(objects[8][5],1)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop(EXT_ELEM_PROP_3,"733",0)
f.write("\n\n-------------------------------------\n            35 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.erase(2)
set.erase(0)
set.erase(1)
f.write('set.prop(PROP_7): ' + str(set.prop(PROP_7)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.add_extend_elem_prop(EXT_ELEM_PROP_10,"-99")
f.write("\n\n-------------------------------------\n            40 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.remove_extend_elem_prop(EXT_ELEM_PROP_1)
set.free_elem_degree()
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_9,0): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_9,0)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_elem_prop(ELEM_PROP_9): ' + str(set.has_elem_prop(ELEM_PROP_9)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.elem_resize(8,975)
set.remove_elem_prop(ELEM_PROP_5)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.remove_extend_elem_prop(EXT_ELEM_PROP_6)
f.write("\n\n-------------------------------------\n            45 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_elem_prop(ELEM_PROP_1)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.elem_prop_index(ELEM_PROP_4): ' + str(set.elem_prop_index(ELEM_PROP_4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.prop_name(6)
set.push_back(objects[8][7])
set.remove_extend_elem_prop(EXT_ELEM_PROP_2)
set.remove_extend_elem_prop(EXT_ELEM_PROP_8)
f.write("\n\n-------------------------------------\n            50 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.add_elem_prop(ELEM_PROP_4,776)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.copy_extend_elem_prop_row(set2,1,1)
set.erase(2)
set.push_back(objects[8][8], ext_prop_row_maps[2])
set.elem_resize(2,480)
f.write("\n\n-------------------------------------\n            55 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.add_extend_elem_prop(EXT_ELEM_PROP_8,"-99")
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.insert(objects[2][4],0)
f.write('set.has_elem_prop(ELEM_PROP_7): ' + str(set.has_elem_prop(ELEM_PROP_7)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop_row(ext_prop_row_maps[0],0)
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.push_back(objects[2][2])
f.write("\n\n-------------------------------------\n            60 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.copy_extend_elem_prop_row(set2,0,2)
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_3,3): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_3,3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_prop(EXT_ELEM_PROP_4,"-99")
set.remove_elem_prop(ELEM_PROP_2)
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.prop_name(2)
set.remove_elem_prop(ELEM_PROP_4)
f.write("\n\n-------------------------------------\n            65 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop_row(ext_prop_row_maps[0],1)
set.prop_name(2)
f.write('set.prop_index(PROP_4): ' + str(set.prop_index(PROP_4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_3): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
set.remove_extend_elem_prop(EXT_ELEM_PROP_7)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
f.write("\n\n-------------------------------------\n            70 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_8): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_8)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_props(set2)
set.insert(objects[6][7],2)
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.copy_extend_elem_prop_row(set2,3,5)
set.copy_extend_elem_prop_row(set2,4,2)
set.get_extend_elem_prop_row(4)
f.write("\n\n-------------------------------------\n            75 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_8,140)
set.set_extend_elem_prop(EXT_ELEM_PROP_4,"138",2)
set.get_extend_elem_prop_row(3)
set.get_extend_elem_prop_row(2)
set.set_extend_elem_prop_row(ext_prop_row_maps[5],5)
f.write("\n\n-------------------------------------\n            80 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop(EXT_ELEM_PROP_5,"667",2)
set.add_extend_elem_prop(EXT_ELEM_PROP_2,"-99")
set.insert(objects[1][2],2)
set.add_extend_elem_prop(EXT_ELEM_PROP_8,"-99")
set.remove_prop(PROP_5)
f.write("\n\n-------------------------------------\n            85 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.remove_extend_elem_prop(EXT_ELEM_PROP_6)
set.insert(objects[8][9],3)
set.resize(1,277,5)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_prop(EXT_ELEM_PROP_6,"-99")
set.prop_name(0)
f.write("\n\n-------------------------------------\n            90 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.erase(0)
set.prop_name(3)
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.elem_resize(8,926)
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_extend_elem_prop(EXT_ELEM_PROP_9)
set.remove_prop(PROP_4)
f.write("\n\n-------------------------------------\n            95 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.remove_extend_elem_prop(EXT_ELEM_PROP_5)
set.add_prop(PROP_5,902)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_10,182)
set.push_back(objects[8][0], ext_prop_row_maps[2])
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_index(PROP_9): ' + str(set.prop_index(PROP_9)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_4,779)
f.write("\n\n-------------------------------------\n            100 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_2): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_2)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_3,22)
set.resize(3,137,0)
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_10): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_10)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop(EXT_ELEM_PROP_8,"308",0)
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_10,2): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_10,2)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.erase(1)
set.erase(1)
f.write("\n\n-------------------------------------\n            105 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_3,0): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_3,0)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[8][5], ext_prop_row_maps[4])
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop(PROP_1): ' + str(set.prop(PROP_1)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.get_extend_elem_prop_row(0)
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.elem_resize(9,179)
f.write("\n\n-------------------------------------\n            110 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_10,1): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_10,1)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[9][1], ext_prop_row_maps[3])
set.erase(0)
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop(PROP_3): ' + str(set.prop(PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[9][8])
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_prop(PROP_2)
set.get_extend_elem_prop_row(0)
f.write("\n\n-------------------------------------\n            115 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.add_extend_elem_prop(EXT_ELEM_PROP_5,"-99")
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.prop_name(2)
set.prop_name(0)
set.erase(0)
set.copy_extend_elem_prop_row(set2,4,1)
f.write("\n\n-------------------------------------\n            120 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.free_elem_degree()
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_prop(PROP_8)
f.write('set.prop_index(PROP_10): ' + str(set.prop_index(PROP_10)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_extend_elem_prop(EXT_ELEM_PROP_7)
set.add_extend_elem_prop(EXT_ELEM_PROP_1,"-99")
f.write("\n\n-------------------------------------\n            125 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.elem_resize(4,873)
set.remove_extend_elem_prop(EXT_ELEM_PROP_3)
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_props(set2)
set.free_elem_degree()
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_2,0): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_2,0)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.insert(objects[5][3],1)
f.write("\n\n-------------------------------------\n            130 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[4][7], ext_prop_row_maps[3])
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[4][0], ext_prop_row_maps[7])
set.push_back(objects[6][6], ext_prop_row_maps[2])
set.elem_resize(7,192)
set.insert(objects[7][9],1)
f.write("\n\n-------------------------------------\n            135 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.prop(PROP_3): ' + str(set.prop(PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.insert(objects[7][1],0)
set.add_extend_elem_prop(EXT_ELEM_PROP_6,"-99")
f.write('set.has_elem_prop(ELEM_PROP_3): ' + str(set.has_elem_prop(ELEM_PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.prop(PROP_5): ' + str(set.prop(PROP_5)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_4): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.elem_resize(6,44)
f.write("\n\n-------------------------------------\n            140 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.get_extend_elem_prop_row(2)
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop_row(ext_prop_row_maps[0],6)
set.add_extend_elem_props(set2)
set.resize(9,561,0)
f.write('set.prop_index(PROP_3): ' + str(set.prop_index(PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[6][8])
f.write("\n\n-------------------------------------\n            145 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.insert(objects[6][0],5)
set.add_extend_elem_props(set2)
set.push_back(objects[6][7])
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.prop_name(7)
set.push_back(objects[6][1], ext_prop_row_maps[4])
f.write("\n\n-------------------------------------\n            150 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_elem_prop(ELEM_PROP_10): ' + str(set.has_elem_prop(ELEM_PROP_10)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.resize(5,969,0)
f.write('set.has_prop(PROP_8): ' + str(set.has_prop(PROP_8)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.elem_resize(2,367)
set.add_prop(PROP_2,692)
set.add_prop(PROP_8,147)
set.resize(8,245,0)
f.write("\n\n-------------------------------------\n            155 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_5,3): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_5,3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.prop_name(6)
set.remove_extend_elem_prop(EXT_ELEM_PROP_8)
set.add_extend_elem_props(set2)
set.get_extend_elem_prop_row(5)
set.set_extend_elem_prop(EXT_ELEM_PROP_2,"640",0)
f.write("\n\n-------------------------------------\n            160 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
set.get_extend_elem_prop_row(0)
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_9): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_9)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_extend_elem_prop(EXT_ELEM_PROP_2)
f.write('set.prop(PROP_9): ' + str(set.prop(PROP_9)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
set.freeze_elem_degree()
f.write("\n\n-------------------------------------\n            165 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.remove_extend_elem_prop(EXT_ELEM_PROP_6)
set.remove_prop(PROP_9)
set.push_back(objects[2][6])
set.remove_prop(PROP_8)
f.write("\n\n-------------------------------------\n            170 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.resize(1,823,0)
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.elem_resize(1,218)
set.prop_name(4)
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.copy_extend_elem_prop_row(set2,4,0)
f.write('set.prop_index(PROP_3): ' + str(set.prop_index(PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.erase(0)
f.write("\n\n-------------------------------------\n            175 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.remove_extend_elem_prop(EXT_ELEM_PROP_7)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.elem_resize(2,672)
set.prop_name(0)
set.prop_name(2)
set.elem_resize(4,946)
f.write("\n\n-------------------------------------\n            180 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.prop_name(7)
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_extend_elem_prop(EXT_ELEM_PROP_4)
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_prop(PROP_8,859)
set.add_prop(PROP_9,835)
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_prop(EXT_ELEM_PROP_10,"-99")
f.write("\n\n-------------------------------------\n            185 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.has_prop(PROP_9): ' + str(set.has_prop(PROP_9)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_prop(PROP_2): ' + str(set.has_prop(PROP_2)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_8): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_8)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_3): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.resize(9,576,0)
set.insert(objects[4][4],1)
set.add_extend_elem_prop(EXT_ELEM_PROP_7,"-99")
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_9,6): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_9,6)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop_row(ext_prop_row_maps[6],8)
f.write("\n\n-------------------------------------\n            190 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.remove_prop(PROP_6)
set.set_extend_elem_prop(EXT_ELEM_PROP_7,"493",2)
set.elem_resize(9,337)
set.add_prop(PROP_6,153)
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
f.write("\n\n-------------------------------------\n            195 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_index(PROP_3): ' + str(set.prop_index(PROP_3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_props(set2)
set.erase(4)
set.add_extend_elem_prop(EXT_ELEM_PROP_1,"-99")
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_5,4): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_5,4)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_index(PROP_10): ' + str(set.prop_index(PROP_10)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.erase(8)
set.set_extend_elem_prop_row(ext_prop_row_maps[0],2)
f.write("\n\n-------------------------------------\n            200 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_2): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_2)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_1): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_1)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_9,3): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_9,3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
f.write('set.has_prop(PROP_2): ' + str(set.has_prop(PROP_2)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_prop(PROP_1): ' + str(set.has_prop(PROP_1)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.copy_extend_elem_prop_row(set2,0,1)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.get_extend_elem_prop_row(6)
f.write('set.num_props(): ' + str(set.num_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.elem_prop_keys(): ' + str(set.elem_prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_props(set2)
f.write("\n\n-------------------------------------\n            205 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.elem_resize(2,89)
set.push_back(objects[2][6], ext_prop_row_maps[3])
set.elem_resize(5,359)
set.free_elem_degree()
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.remove_extend_elem_prop(EXT_ELEM_PROP_10)
f.write("\n\n-------------------------------------\n            210 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_extend_elem_prop(EXT_ELEM_PROP_1): ' + str(set.has_extend_elem_prop(EXT_ELEM_PROP_1)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop_index(PROP_7): ' + str(set.prop_index(PROP_7)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.insert(objects[6][7],5)
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop_row(ext_prop_row_maps[3],0)
set.add_extend_elem_prop(EXT_ELEM_PROP_6,"-99")
set.remove_prop(PROP_4)
f.write('set.num_extend_elem_props(): ' + str(set.num_extend_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_props(set2)
f.write("\n\n-------------------------------------\n            215 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.num_elem_props(): ' + str(set.num_elem_props()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.add_extend_elem_prop(EXT_ELEM_PROP_5,"-99")
set.remove_prop(PROP_7)
set.add_extend_elem_props(set2)
set.elem_resize(5,955)
set.resize(4,369,0)
f.write("\n\n-------------------------------------\n            220 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.add_prop(PROP_4,364)
set.freeze_elem_degree()
elem_props = set.get_elem_prop_header(); (objects,prop_row_maps,prop_rows) = recreate_elem_prop_objects(elem_props)
set.add_prop(PROP_7,495)
set.free_elem_degree()
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[6][6])
f.write("\n\n-------------------------------------\n            225 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
f.write('set.size(): ' + str(set.size()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.free_elem_degree()
f.write('set.vsize(): ' + str(set.vsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop(EXT_ELEM_PROP_5,3): ' + str(set.get_extend_elem_prop(EXT_ELEM_PROP_5,3)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.append_extend_elem_props(set2)
f.write('set.prop_keys(): ' + str(set.prop_keys()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.push_back(objects[0][4])
set.add_extend_elem_props(set2)
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.get_extend_elem_prop_header(): ' + str(set.get_extend_elem_prop_header()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.prop(PROP_10): ' + str(set.prop(PROP_10)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.copy_extend_elem_prop_row(set2,3,4)
f.write("\n\n-------------------------------------\n            230 MODFICATIONS             \n-------------------------------------\n" + str(set) + "\n\n")
set.get_extend_elem_prop_row(1)
f.write('set.prop_index(PROP_10): ' + str(set.prop_index(PROP_10)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.has_elem_prop(ELEM_PROP_8): ' + str(set.has_elem_prop(ELEM_PROP_8)).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.set_extend_elem_prop(EXT_ELEM_PROP_10,"898",1)
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
f.write('set.bsize(): ' + str(set.bsize()).replace("', '"," ").replace("['","[ ").replace("']"," ]") + '\n')
set.get_extend_elem_prop_row(1)


#=====================================================================================================================
# Generated functions end here
#=====================================================================================================================

f.write('\n\n-------------------------------------\n             FINAL PRINT             \n-------------------------------------\n')

f.write(str(set))

print 'Ran python test successfully!'

f.write('\n')

f.close()
