#!/bin/bash

DIR=$1

if [ "${#DIR}" = 0 ]; then
  DIR='.'
fi

for f in `ls $DIR/*.tck`; do 

  if [ -h $f ]; then
    file=`readlink $f`
  else
    file=$f
  fi

  file_strip=${file##*/}

  select_fibres $file /tmp/$file_strip.txt

  sed -i 's/base_intensity: 0/base_intensity: 1/g' /tmp/$file_strip.txt

  select_fibres /tmp/$file_strip.txt $file

done
