#!/usr/bin/env bash
invivo_sampling.py --dataset donald/images/corpus_callosum.mif --num_runs 5
invivo_sampling.py --dataset donald/images/fornix.mif --num_runs 5
invivo_sampling.py --dataset heath/images/corpus_callosum.mif --num_runs 5
invivo_sampling.py --dataset heath/images/fornix.mif --num_runs 5
invivo_sampling.py --dataset lisa/images/corpus_callosum.mif --num_runs 5
invivo_sampling.py --dataset lisa/images/fornix.mif --num_runs 5
invivo_sampling.py --dataset donald/images/corpus_callosum.60.mif --num_runs 5
invivo_sampling.py --dataset donald/images/fornix.60.mif --num_runs 5
invivo_sampling.py --dataset heath/images/corpus_callosum.60.mif --num_runs 5
invivo_sampling.py --dataset heath/images/fornix.60.mif --num_runs 5
invivo_sampling.py --dataset lisa/images/corpus_callosum.60.mif --num_runs 5
invivo_sampling.py --dataset lisa/images/fornix.60.mif --num_runs 5
invivo_sampling.py --dataset donald/images/corpus_callosum.20.mif --num_runs 5
invivo_sampling.py --dataset donald/images/fornix.20.mif --num_runs 5
