#!/usr/bin/env bash

rm ~/Desktop/intensities; 
for n in `seq 30`; do 
    generate_image /home/tclose/fouts/params/fibre/tract/test_configurations/x-large.tct ~/Desktop/intens_calc/$n.mif -clean --exp_num_width $n; 
    maxb0 ~/Desktop/intens_calc/$n.mif >> ~/Desktop/intensities; 
    echo " " >> ~/Desktop/intensities; 
done
python /home/tclose/fouts/python/plot_base_signal.py

