#!/bin/bash

#if [ $# -le 1 ]; then
#  echo "At least 1 argument need to be supplied to $0 ($# supplied)."
#  exit -1
#fi

if [ ${1##*.} == 'txt' ]; then

  new_fibres $1 ${@:2}

  vi $1

else

  TEMP_TXT_FILE=/tmp/${1##*/}.txt

  #Export fibres file to a temporary text equivalent.
  new_fibres $TEMP_TXT_FILE ${@:2} 

  #Edit with vi
  vi $TEMP_TXT_FILE 

  #Import fibres back to output location
  select_fibres $TEMP_TXT_FILE $1

  #Cleanup temporary file
  rm $TEMP_TXT_FILE

fi
