#!/bin/bash

directory_name=$1

for file in `ls $directory_name/*.frr`; do 

   svn move $file ${file/%.frr/.str}; 

done

for file in `ls $directory_name/*.frrx`; do 

   svn move $file ${file/%.frrx/.strx}; 

done

for file in `ls $directory_name/*.frrxx`; do 

   svn move $file ${file/%.frrxx/.strxx}; 

done


svn commit -m "renaming '.frr' to '.str' in directory $directory_name"